Lession 4
Kirninn/Geekshop pull request #4
Opened 2021-03-08 11:54 UTC by Kirninn

2021-03-11 13:55 UTC, Vokler requested changes

2021-03-11 13:55 UTC, Vokler commented on authapp/urls.py
> +   path('/login', login, name='login'),
Слэши не должны быть в начале. Они должны быть закрывающимися и в конце. Посмотрите пример, который мы делали на уроке

2021-03-11 16:43 UTC, Kirninn commented on authapp/urls.py
> +   path('/login', login, name='login'),
Исправлено.

2021-03-17 16:51 UTC, Vokler approved these changes

2021-03-17 16:51 UTC, merged